services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    profiles: ["dev"]

  postgres:
    image: postgres:15
    container_name: feature_votes_database
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: feature_votes
    ports:
      - "5432:5432"
