# Kubernetes Service for SecDev Course App
apiVersion: v1
kind: Service
metadata:
  name: secdev-app
  namespace: secdev
  labels:
    app: secdev-app
spec:
  type: ClusterIP
  selector:
    app: secdev-app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
